media: 
  input: assets/img
  output: /
content:
  - name: posts
    label: Posts
    type: collection
    filename: '{year}-{month}-{day}-{primary}.markdown'
    path: _posts
    fields:
     - name: layout
       type: string
       hidden: true
       default: post
     - name: title
       label: Title
       type: string
     - name: img
       label: Image
       type: image
       options:
         path: ""
     - name: date
       label: Date
       type: date
       options:
         format: yyyy-MM-dd HH:mm
         time: true
     - name: description
       label: Description
       type: string
     - name: tag
       label: Tags
       type: string
     - name: body
       label: Body
       type: rich-text